-- AGRO-FLOPPY (Zafra AI) — Esquema inicial auditado
-- Supabase project: skxgdeogffuaafkdynyk
-- Aplicar en: SQL Editor de Supabase o via scripts/apply_schema.py

BEGIN;

-- ---------------------------------------------------------------------------
-- Extensiones
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ---------------------------------------------------------------------------
-- Catálogo: cultivos
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cultivos (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR(50)  NOT NULL UNIQUE,
    nombre_cientifico   VARCHAR(120),
    descripcion         TEXT,
    activo              BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Catálogo: tipos de evaluación (alineado con TipoEvaluacionEnum del backend)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tipos_evaluacion (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo              VARCHAR(40)  NOT NULL UNIQUE,
    nombre              VARCHAR(80)  NOT NULL,
    descripcion         TEXT,
    activo              BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Usuarios (productores, agrónomos, administradores)
-- auth_user_id reservado para integración futura con Supabase Auth
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS usuarios (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_user_id        UUID UNIQUE,
    nombre              VARCHAR(120) NOT NULL,
    email               VARCHAR(255) NOT NULL UNIQUE,
    rol                 VARCHAR(30)  NOT NULL DEFAULT 'productor'
        CHECK (rol IN ('productor', 'agronomo', 'administrador')),
    activo              BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Lugares de referencia (demo Santa Cruz — frontend/js/santa-cruz-data.js)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lugares (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo              VARCHAR(80)  NOT NULL UNIQUE,
    nombre              VARCHAR(200) NOT NULL,
    tipo                VARCHAR(30)  NOT NULL
        CHECK (tipo IN ('agricola', 'ganadera', 'mixta')),
    cultivo_id          INTEGER REFERENCES cultivos(id) ON DELETE SET NULL,
    descripcion         TEXT,
    latitud             DOUBLE PRECISION NOT NULL,
    longitud            DOUBLE PRECISION NOT NULL,
    hectareas           NUMERIC(12, 2),
    ganado              INTEGER,
    zona                VARCHAR(100),
    es_demo             BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Polígonos de campos / potreros (mapa demo)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS campos_poligonos (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo              VARCHAR(80)  NOT NULL UNIQUE,
    nombre              VARCHAR(200) NOT NULL,
    tipo                VARCHAR(30)  NOT NULL
        CHECK (tipo IN ('agricola', 'ganadera', 'mixta')),
    coordenadas         JSONB        NOT NULL,
    es_demo             BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Evaluaciones agronómicas (POST /evaluar)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS evaluaciones (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id              INTEGER REFERENCES usuarios(id) ON DELETE SET NULL,
    cultivo_id              INTEGER NOT NULL REFERENCES cultivos(id) ON DELETE RESTRICT,
    tipo_evaluacion_id      INTEGER NOT NULL REFERENCES tipos_evaluacion(id) ON DELETE RESTRICT,
    lugar_id                INTEGER REFERENCES lugares(id) ON DELETE SET NULL,
    ubicacion               VARCHAR(255) NOT NULL,
    latitud                 DOUBLE PRECISION,
    longitud                DOUBLE PRECISION,
    texto                   VARCHAR(5000),
    audio_nombre            VARCHAR(255),
    audio_mime_type         VARCHAR(100),
    audio_tamano_bytes      BIGINT,
    audio_storage_path      VARCHAR(512),
    recomendacion           TEXT,
    explicacion             TEXT,
    clima_json              JSONB,
    estado                  VARCHAR(30) NOT NULL DEFAULT 'recibida'
        CHECK (estado IN ('recibida', 'procesando', 'completada', 'error')),
    mensaje                 TEXT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_evaluacion_coords
        CHECK (
            (latitud IS NULL AND longitud IS NULL)
            OR (latitud BETWEEN -90 AND 90 AND longitud BETWEEN -180 AND 180)
        )
);

-- ---------------------------------------------------------------------------
-- Caché de clima (OpenWeather — pendiente de integración)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clima_cache (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    latitud             DOUBLE PRECISION NOT NULL,
    longitud            DOUBLE PRECISION NOT NULL,
    datos               JSONB        NOT NULL,
    fetched_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    expires_at          TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_clima_cache_coords UNIQUE (latitud, longitud)
);

-- ---------------------------------------------------------------------------
-- Índices
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_usuarios_email ON usuarios(email);
CREATE INDEX IF NOT EXISTS idx_usuarios_auth_user ON usuarios(auth_user_id) WHERE auth_user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_lugares_zona ON lugares(zona);
CREATE INDEX IF NOT EXISTS idx_lugares_coords ON lugares(latitud, longitud);

CREATE INDEX IF NOT EXISTS idx_evaluaciones_cultivo ON evaluaciones(cultivo_id);
CREATE INDEX IF NOT EXISTS idx_evaluaciones_tipo ON evaluaciones(tipo_evaluacion_id);
CREATE INDEX IF NOT EXISTS idx_evaluaciones_usuario ON evaluaciones(usuario_id);
CREATE INDEX IF NOT EXISTS idx_evaluaciones_estado ON evaluaciones(estado);
CREATE INDEX IF NOT EXISTS idx_evaluaciones_created ON evaluaciones(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_evaluaciones_coords ON evaluaciones(latitud, longitud);

CREATE INDEX IF NOT EXISTS idx_clima_cache_expires ON clima_cache(expires_at);

-- ---------------------------------------------------------------------------
-- Trigger: updated_at automático
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_usuarios_updated_at ON usuarios;
CREATE TRIGGER trg_usuarios_updated_at
    BEFORE UPDATE ON usuarios
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_evaluaciones_updated_at ON evaluaciones;
CREATE TRIGGER trg_evaluaciones_updated_at
    BEFORE UPDATE ON evaluaciones
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- Datos semilla: cultivos
-- ---------------------------------------------------------------------------
INSERT INTO cultivos (nombre, nombre_cientifico, descripcion) VALUES
    ('soya', 'Glycine max', 'Cultivo oleaginoso de verano'),
    ('maiz', 'Zea mays', 'Cereal de grano de verano')
ON CONFLICT (nombre) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Datos semilla: tipos de evaluación
-- ---------------------------------------------------------------------------
INSERT INTO tipos_evaluacion (codigo, nombre, descripcion) VALUES
    ('siembra',        'Siembra',        'Ventana óptima, profundidad, densidad, condiciones de suelo'),
    ('fertilizacion',  'Fertilización',  'NPK, micronutrientes, momento de aplicación'),
    ('riego',          'Riego',          'Déficit hídrico, ETc, pronóstico de lluvias'),
    ('plagas',         'Plagas',         'Umbrales de intervención, monitoreo, manejo integrado'),
    ('cosecha',        'Cosecha',        'Humedad de grano, punto de corte, rendimiento estimado')
ON CONFLICT (codigo) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Datos semilla: lugares demo Santa Cruz
-- ---------------------------------------------------------------------------
INSERT INTO lugares (codigo, nombre, tipo, cultivo_id, descripcion, latitud, longitud, hectareas, ganado, zona) VALUES
    ('okinawa-soya',       'Colonia Okinawa — Lote Norte',      'agricola',  (SELECT id FROM cultivos WHERE nombre = 'soya'), 'Referencia histórica de producción de soya en el oriente cruceño.', -17.22, -62.89, 3200, NULL, 'Okinawa'),
    ('montero-maiz',       'Finca El Trigal — Montero',         'agricola',  (SELECT id FROM cultivos WHERE nombre = 'maiz'), 'Zona productiva de maíz en el valle de Montero.', -17.34, -63.25, 1800, NULL, 'Montero'),
    ('san-julian-soya',    'San Julián — Bloque Agrícola Sur',  'agricola',  (SELECT id FROM cultivos WHERE nombre = 'soya'), 'Macrozona agrícola del departamento, alto rendimiento en soya.', -17.78, -62.87, 5400, NULL, 'San Julián'),
    ('portachuelo-mixto',  'Establecimiento Portachuelo',       'mixta',     (SELECT id FROM cultivos WHERE nombre = 'soya'), 'Rotación soya-maíz con retención ganadera en potreros adyacentes.', -17.35, -63.39, 2600, NULL, 'Portachuelo'),
    ('charagua-ganadera',  'Estancia Charagua Sur',             'ganadera',  NULL, 'Pastizales extensivos del Chaco — cría y engorde de ganado.', -19.79, -63.20, 12500, 8500, 'Charagua'),
    ('concepcion-ganadera','Hacienda Concepción',               'ganadera',  NULL, 'Tradición ganadera del norte cruceño, pastoreo rotacional.', -16.08, -62.62, 9800, 6200, 'Concepción'),
    ('pailon-ganadera',    'Campo Los Palmaritos — Pailón',     'ganadera',  NULL, 'Potreros con aguadas naturales, apto para recría.', -17.65, -62.72, 4100, 2800, 'Pailón'),
    ('warnes-agricola',    'Predio Warnes Centro',              'agricola',  (SELECT id FROM cultivos WHERE nombre = 'maiz'), 'Transición agrícola cercana a la carretera a Warnes.', -17.52, -63.17, 950, NULL, 'Warnes'),
    ('buena-vista-soya',   'Finca Buena Vista',                 'agricola',  (SELECT id FROM cultivos WHERE nombre = 'soya'), 'Lotes tecnificados con riego suplementario en época seca.', -17.45, -63.65, 2100, NULL, 'Buena Vista'),
    ('cotoca-mixta',       'Lote Cotoca Este',                  'mixta',     (SELECT id FROM cultivos WHERE nombre = 'maiz'), 'Periurbano: maíz de verano y ganado lechero en margen del Piraí.', -17.75, -62.83, 680, 420, 'Cotoca'),
    ('la-guardia-agricola','Campo La Guardia',                  'agricola',  (SELECT id FROM cultivos WHERE nombre = 'soya'), 'Zona en expansión agrícola hacia el sur metropolitano.', -17.90, -63.32, 1400, NULL, 'La Guardia'),
    ('los-negros-ganadera','Estancia Los Negros',               'ganadera',  NULL, 'Campo ganadero de referencia en la Chiquitanía baja.', -17.74, -63.05, 7200, 5100, 'Los Negros'),
    ('pirai-urbano',       'Parque Agrícola Piraí',             'mixta',     (SELECT id FROM cultivos WHERE nombre = 'maiz'), 'Área periurbana de Santa Cruz — demo de evaluación local.', -17.79, -63.16, 320, 180, 'Piraí — Santa Cruz'),
    ('san-pedro-soya',     'San Pedro — Lote Industrial',       'agricola',  (SELECT id FROM cultivos WHERE nombre = 'soya'), 'Macro lote mecanizado en el eje San Pedro–San Julián.', -18.42, -62.87, 3800, NULL, 'San Pedro')
ON CONFLICT (codigo) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Datos semilla: polígonos demo
-- ---------------------------------------------------------------------------
INSERT INTO campos_poligonos (codigo, nombre, tipo, coordenadas) VALUES
    ('potrero-charagua', 'Potrero Charagua Norte', 'ganadera',
        '[[-19.72,-63.28],[-19.72,-63.12],[-19.86,-63.12],[-19.86,-63.28]]'::jsonb),
    ('lote-san-julian', 'Lote San Julián Oeste', 'agricola',
        '[[-17.74,-62.92],[-17.74,-62.82],[-17.82,-62.82],[-17.82,-62.92]]'::jsonb),
    ('potrero-pailon', 'Potrero Pailón', 'ganadera',
        '[[-17.62,-62.76],[-17.62,-62.68],[-17.68,-62.68],[-17.68,-62.76]]'::jsonb)
ON CONFLICT (codigo) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Row Level Security (Supabase best practice)
-- Backend FastAPI usa DATABASE_URL directo (bypass RLS).
-- Sin políticas = acceso denegado vía Data API hasta implementar auth.
-- ---------------------------------------------------------------------------
ALTER TABLE cultivos          ENABLE ROW LEVEL SECURITY;
ALTER TABLE tipos_evaluacion  ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios          ENABLE ROW LEVEL SECURITY;
ALTER TABLE lugares           ENABLE ROW LEVEL SECURITY;
ALTER TABLE campos_poligonos  ENABLE ROW LEVEL SECURITY;
ALTER TABLE evaluaciones      ENABLE ROW LEVEL SECURITY;
ALTER TABLE clima_cache       ENABLE ROW LEVEL SECURITY;

COMMIT;
