-- Base de conocimiento agronómico (Excel Saul, PDFs, documentos)
-- Migración 002

BEGIN;

CREATE TABLE IF NOT EXISTS documentos (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug            VARCHAR(120) NOT NULL UNIQUE,
    titulo          VARCHAR(255) NOT NULL,
    tipo            VARCHAR(40)  NOT NULL CHECK (tipo IN ('excel', 'pdf', 'json', 'codigo')),
    ruta_origen     VARCHAR(512),
    descripcion     TEXT,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS documento_chunks (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id        INTEGER NOT NULL REFERENCES documentos(id) ON DELETE CASCADE,
    cultivo             VARCHAR(50),
    tipo_evaluacion     VARCHAR(40),
    etiquetas           TEXT[] DEFAULT '{}',
    contenido           TEXT NOT NULL,
    fuente_cita         VARCHAR(512),
    metadata            JSONB DEFAULT '{}',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_documento_chunks_doc ON documento_chunks(documento_id);
CREATE INDEX IF NOT EXISTS idx_documento_chunks_cultivo ON documento_chunks(cultivo);
CREATE INDEX IF NOT EXISTS idx_documento_chunks_tipo ON documento_chunks(tipo_evaluacion);
CREATE INDEX IF NOT EXISTS idx_documento_chunks_etiquetas ON documento_chunks USING GIN (etiquetas);

DROP TRIGGER IF EXISTS trg_documentos_updated_at ON documentos;
CREATE TRIGGER trg_documentos_updated_at
    BEFORE UPDATE ON documentos
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE documentos       ENABLE ROW LEVEL SECURITY;
ALTER TABLE documento_chunks ENABLE ROW LEVEL SECURITY;

COMMIT;
