UBICACIONES = [
    {
        "nombre": "Santa Cruz de la Sierra",
        "departamento": "Santa Cruz",
        "lat": -17.78,
        "lon": -63.18,
        "tipo": "anapo",
        "foreca_location_id": "103904906",
        "foreca_widget_id": "8ufE7r9n6t",
    },
    {
        "nombre": "Cuatro Cañadas",
        "departamento": "Santa Cruz",
        "lat": -17.40,
        "lon": -62.35,
        "tipo": "anapo",
        "foreca_location_id": "108335389",
        "foreca_widget_id": "Y86MxJHLT7",
    },
    {
        "nombre": "San Julián",
        "departamento": "Santa Cruz",
        "lat": -17.78,
        "lon": -62.83,
        "tipo": "anapo",
        "foreca_location_id": "103905453",
        "foreca_widget_id": "uCN1yIUhQQ",
    },
    {
        "nombre": "San Ignacio de Velasco",
        "departamento": "Santa Cruz",
        "lat": -16.37,
        "lon": -60.96,
        "tipo": "anapo",
        "foreca_location_id": "103905658",
        "foreca_widget_id": "s1ZeNoWIw5",
    },
    {
        "nombre": "Okinawa Número Uno",
        "departamento": "Santa Cruz",
        "lat": -17.23,
        "lon": -62.68,
        "tipo": "anapo",
        "foreca_location_id": "103909360",
        "foreca_widget_id": "12D68Zxu2K",
    },
    {
        "nombre": "Sucre",
        "departamento": "Chuquisaca",
        "lat": -19.02,
        "lon": -65.26,
        "tipo": "capital",
    },
    {
        "nombre": "Cochabamba",
        "departamento": "Cochabamba",
        "lat": -17.41,
        "lon": -66.17,
        "tipo": "capital",
    },
    {
        "nombre": "Oruro",
        "departamento": "Oruro",
        "lat": -17.96,
        "lon": -67.11,
        "tipo": "capital",
    },
    {
        "nombre": "Potosí",
        "departamento": "Potosí",
        "lat": -19.62,
        "lon": -65.75,
        "tipo": "capital",
    },
    {
        "nombre": "Tarija",
        "departamento": "Tarija",
        "lat": -21.53,
        "lon": -64.73,
        "tipo": "capital",
    },
    {
        "nombre": "Trinidad",
        "departamento": "Beni",
        "lat": -14.83,
        "lon": -64.90,
        "tipo": "capital",
    },
    {
        "nombre": "Cobija",
        "departamento": "Pando",
        "lat": -11.02,
        "lon": -68.77,
        "tipo": "capital",
    },
    {
        "nombre": "La Paz",
        "departamento": "La Paz",
        "lat": -16.50,
        "lon": -68.15,
        "tipo": "capital",
    },
    {
        "nombre": "El Alto",
        "departamento": "La Paz",
        "lat": -16.52,
        "lon": -68.17,
        "tipo": "capital",
    },
    {
        "nombre": "Riberalta",
        "departamento": "Beni",
        "lat": -10.98,
        "lon": -66.10,
        "tipo": "capital",
    },
]
